export const createPoll: string;
export const form: string;
export const title: string;
export const fieldsList: string;
export const field: string;
export const input: string;
export const label: string;
export const line: string;
export const plus: string;
